[tool.black]
line-length = 120
[isort]
profile = "black"
[build-system]
requires = ["setuptools>=79.0","setuptools-scm>=8.3"]
build-backend = "setuptools.build_meta"
[tool.pytest.ini_options]
markers = ["data: uses test data (deselect with '-m \"not data\"')",]
